config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments
  resources :categories
devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_posts
    end
  end

  root 'posts#home'

  get '/.well-known/acme-challenge/:id' => 'static_pages#certbot'

  get '/about' => 'static_pages#about'

  get '/link' => 'static_pages#link'

  get '/privacy' => 'static_pages#privacy'

  get '/terms' => 'static_pages#terms'

  get '/popular' => 'posts#popular', as: 'popular'

  get '/aoyama' => 'posts#aoyama', as: 'aoyama'

  get '/shibuya' => 'posts#shibuya', as: 'shibuya'

  get '/ginza' => 'posts#ginza', as: 'ginza'

  get '/other' => 'posts#other', as: 'other'

  get '/product' => 'posts#product', as: 'product'

  mount Commontator::Engine => '/commontator' #コメント機能のルート設定

  resources :posts

  post 'like/:post_id' => 'likes#like', as: 'like'
  delete 'unlike/:post_id' => 'likes#unlike', as: 'unlike'

  %w(get put patch post delete).each do |method|
  send(method, '*something', controller: :application, action: :render_404)
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :user_id, :scope => :post_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def like
    @post = Post.find(params[:post_id])
    like = current_user.likes.build(post_id: @post.id)
    like.save


  end

  def unlike
    @post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id: @post.id)
    #like.destroy
    Like.delete_all(post_id: @post.id, user_id: current_user)

  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_links.html.erb
<% if user_signed_in? %>
<% if current_user.likes.find_by(post_id: post.id) %>
     <%= link_to (content_tag(:i, '', class: 'fa fa-heart')),unlike_path(post.id), method: :delete, remote: true %>
      <%=  post.likes.count %> Like
  <% else %>
    <%= link_to (content_tag(:i, '', class: 'fa fa-heart-o')),like_path(post.id), method: :post, remote: true %>
     <%=  post.likes.count %>  Like
  <% end %>
<% else %>
  <%=  post.likes.count %>  Like
<% end %>

app/views/likes/like.js.erb
$('#like-link<%= @post.id %>').html('<%= escape_javascript(render("likes/like_links", post: @post )) %>');

app/views/likes/unlike.js.erb
$('#like-link<%= @post.id %>').html('<%= escape_javascript(render("likes/like_links", post: @post )) %>');