config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments
  resources :categories
devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_posts
    end
  end

  root 'posts#home'

  get '/.well-known/acme-challenge/:id' => 'static_pages#certbot'

  get '/about' => 'static_pages#about'

  get '/link' => 'static_pages#link'

  get '/privacy' => 'static_pages#privacy'

  get '/terms' => 'static_pages#terms'

  get '/popular' => 'posts#popular', as: 'popular'

  get '/aoyama' => 'posts#aoyama', as: 'aoyama'

  get '/shibuya' => 'posts#shibuya', as: 'shibuya'

  get '/ginza' => 'posts#ginza', as: 'ginza'

  get '/other' => 'posts#other', as: 'other'

  get '/product' => 'posts#product', as: 'product'

  mount Commontator::Engine => '/commontator' #コメント機能のルート設定

  resources :posts

  post 'like/:post_id' => 'likes#like', as: 'like'
  delete 'unlike/:post_id' => 'likes#unlike', as: 'unlike'

  %w(get put patch post delete).each do |method|
  send(method, '*something', controller: :application, action: :render_404)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  has_many :posts, dependent: :destroy #ユーザーと一緒にポストは破棄される
  has_many :likes
  has_many :like_posts, through: :likes, source: :post
  acts_as_commontator #コメント機能の関連づけ

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first


    if user.nil?
        user = User.new(
          uid:       auth.uid,
          name:      auth.info.name,
          image_url: auth.info.image,
          provider:  auth.provider,
          email:     User.dummy_email(auth),
          password:  Devise.friendly_token[4, 30]
        )
        user.skip_confirmation!
        user.save!
    end

    # unless user
    #   user = User.create(
    #     uid:       auth.uid,
    #     name:      auth.info.name,
    #     image_url: auth.info.image,
    #     provider:  auth.provider,
    #     email:     User.dummy_email(auth),
    #     password:  Devise.friendly_token[4, 30]
    #   )
    # end

    user
  end

  def self.find_for_google_oauth2(auth)
    user = User.where(email: auth.info.email).first

    unless user
      user = User.create(name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[4, 30])
    end
    user
  end

  def set_image(file)#プロフィール画像を保存するためのインスタンスメソッド 12/12
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_avatars/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.avatar = file_name
    end
  end

  private

    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def twitter
    callback_from :twitter
  end

  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"])

    # 保存済みかどうかのチェック
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  private
    def callback_from(provider)
      provider = provider.to_s
      @user = User.find_for_oauth(request.env['omniauth.auth'])
      if @user.persisted?
        cookies.permanent[:xxx_logined] = { value: @user.created_at }
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
        sign_in_and_redirect @user, event: :authentication
      else
        if provider == 'twitter'
          session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
        else
          session["devise.facebook_data"] = request.env["omniauth.auth"]
        end
        redirect_to new_user_registration_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :like_posts]
  before_action :user_signed_in, only: [:edit, :update] #ユーザープロフ編集にはログインが必要。11/20 arthur
  before_action :correct_user, only: [:edit, :update] #正しいユーザーかの確認 11/20 arthur
  before_action :sns_user, only: [:edit, :update] #snsユーザーの編集禁止
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

    @posts = @user.posts #11/19 Mypostsを表示
  end



  def create #avatarの条件分岐
    @user = User.new(user_params)
    file = params[:user][:avatar]
    @user.set_image(file)

  end

  # GET /users/new
  # def new
  #   @user = User.new
  # end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    file = params[:user][:avatar]
    @user.set_image(file)

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  def like_posts
    @posts = @user.like_posts
    @title = "My favorite"
    render '_user_like_posts'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end

    #正しいユーザーかどうかを確認する 11/20 arthur
    def correct_user
      user = User.find(params[:id])
      if current_user != user
        redirect_to root_path, alert: 'Not allowed,許可されていないページです'
      end
    end

    def sns_user
      user = User.find(params[:id])
      if !user.provider.nil?
        redirect_to root_path, alert: 'Not allowed,許可されていないページです'
      end
    end



end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/users/_form.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--1-col"></div>
  <div class="mdl-cell mdl-cell--10-col">
    <h2 class="mdl-typography--display-2 mdl-typography--font-thin">Editing User</h2>
    <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
    <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
      </ul>
    <% end %>
    <div class="description">
      <!-- <p>*各項目は全て必須</p> -->
    </div>
    <div id="post">
      <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--12-col">
          <form action="#">

            <div class="mdl-textfield">
              <%= f.label :avatar, class: "input-label" %>
              <%= f.file_field :avatar %>
              <%= f.hidden_field :user_id, value: current_user.id %>
            </div>


            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <%= f.text_area :name, class: "mdl-textfield__input"%>
              <%= f.label :name, class: "mdl-textfield__label" %>
            </div>


            <!-- <div class="mdl-textfield mdl-js-textfield">
              <textarea class="mdl-textfield__input" type="text" rows="2" id="text7"></textarea>
              <label class="mdl-textfield__label" for="text7">Address(*required)</label>
            </div> -->

            <%= f.submit "Profile Update", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" %>
          </form>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="mdl-cell mdl-cell--1-col"></div>
</div>

app/views/users/_user_like_posts.html.erb
<ul class="posts">
  
  <h2><%= @title %></h2>
 <%= render @posts %> 
  
</ul>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= avatar_for(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_session_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--1-col"></div>
  <div class="mdl-cell mdl-cell--10-col">
  <% if @user.provider.nil? %>
  <p class="avatar"><%= avatar_for(@user) %></p>
  <% else %>
  <p class="avatar"><%= image_tag @user.image_url %></p>
  <% end %>
  <h2 class="mdl-typography--display-2 mdl-typography--font-thin"><%= @user.name %></h2>
    <p><%= @user.name %> Like Posts:
 <%= link_to @user.likes.count, like_posts_user_path(@user.id) %>
</P>
<% if correct_user?(@user) %> <!--ユーザーが同一の場合だけEDITボタンが出るapprecationHelperのcorrect_user?を定義-->
<% if current_user.provider.nil? %>
<%= link_to 'Profile edit', edit_user_path(@user), class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"%>
<% end %>
<% end %>


<h3><%= @user.name %>'s Posts:</h3>
    <div class="mdl-grid">
    <% @posts.each do |post| %>
      <div class="mdl-cell mdl-cell--6-col">
        <div class="demo-card-square mdl-card mdl-shadow--2dp">
          <div class="category category-shibuya"><%= link_to post.category.name, [post.category.name]%>
          </div>
          <div class="mdl-card__title mdl-card--expand" style="background: url('<%= post.post_attachments.first.picture %>') bottom center no-repeat #fff;">
            <h2 class="mdl-card__title-text"><%= post.title %></h2>
          </div>
          <div class="mdl-card__supporting-text">
            <%= post.content.truncate(15, separator: '.')%>
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <a href="<%= post_path(post.id) %>" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" data-upgraded=",MaterialButton,MaterialRipple">
              View more
              <span class="mdl-button__ripple-container"><span class="mdl-ripple"></span></span></a>
            <span id="like-link<%= post.id %>" class="like_box">
              <%= render "likes/like_links", post: post %>
              </span>
          </div>
        </div>
      </div>
      <% end %>
    </div>

  </div>
  <div class="mdl-cell mdl-cell--1-col"></div>
</div>