config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments
  resources :categories
devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_posts
    end
  end

  root 'posts#home'

  get '/.well-known/acme-challenge/:id' => 'static_pages#certbot'

  get '/about' => 'static_pages#about'

  get '/link' => 'static_pages#link'

  get '/privacy' => 'static_pages#privacy'

  get '/terms' => 'static_pages#terms'

  get '/popular' => 'posts#popular', as: 'popular'

  get '/aoyama' => 'posts#aoyama', as: 'aoyama'

  get '/shibuya' => 'posts#shibuya', as: 'shibuya'

  get '/ginza' => 'posts#ginza', as: 'ginza'

  get '/other' => 'posts#other', as: 'other'

  get '/product' => 'posts#product', as: 'product'

  mount Commontator::Engine => '/commontator' #コメント機能のルート設定

  resources :posts

  post 'like/:post_id' => 'likes#like', as: 'like'
  delete 'unlike/:post_id' => 'likes#unlike', as: 'unlike'

  %w(get put patch post delete).each do |method|
  send(method, '*something', controller: :application, action: :render_404)
  end

end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
  mount_uploader :picture,PictureUploader #Postsモデルに画像を追加
  belongs_to :post
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:new,:index, :show, :create, :edit, :update, :destroy]
  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
  respond_to do |format|
    if @post_attachment.update(post_attachment_params)
      format.html { redirect_to @post_attachment.post, notice: 'Pictures was successfully updated.' }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_attachments_url, notice: 'Post attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    def admin_user
      redirect_to(root_url)unless current_user.admin?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:id,:post_id, :picture)
    end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/post_attachments/_form.html.erb
<%= image_tag @post_attachment.picture %>
<%= form_for(@post_attachment) do |f| %>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit "Save File" %>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<h1>Editing Post Attachment</h1>

<%= render 'form' %>

app/views/post_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_attachments.each do |post_attachment| %>
      <tr>
        <td><%= post_attachment.post_id %></td>
        <td><%= post_attachment.picture %></td>
        <td><%= link_to 'Show', post_attachment %></td>
        <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></td>
        <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post attachment', new_post_attachment_path %>

app/views/post_attachments/new.html.erb
<h1>New Post Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_attachment.post_id %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @post_attachment.picture %>
</p>

<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
<%= link_to 'Back', post_attachments_path %>